config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'translate#index'
  post 'translating_nmt', to: 'translate#translate_nmt'
  post 'translating_smt', to: 'translate#translate_smt'
  post 'translating',     to: 'translate#translate'
  post 'clearing',        to: 'translate#clear'
  post 'marking',         to: 'translate#mark'

  get  'cn-to-vi',          to: 'translate_cn_to_vi#index'
  post 'translating_cn_vi', to: 'translate_cn_to_vi#translate'
  post 'clearing_cn_vi',    to: 'translate_cn_to_vi#clear'
  post 'marking_cn_vi',     to: 'translate_cn_to_vi#mark'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def read_src_file(path)
    src = ''
    File.open(path, "r") do |f|
      src =  f.readline
    end
    src
  end

  def read_tgt_file(path)
    tgt = ''
    File.open(path, "r") do |f|
      tgt =  f.readline
    end
    tgt
  end

  def read_bleu_file(path)
    bleu = ''
    File.open(path, "r") do |f|
      bleu =  f.readline
    end
    res = bleu.match(/[0-9]*\.[0-9]{2}|^[0-9]*\.[0-9]{2}[^0-9]/)
  end
end

app/controllers/translate_cn_to_vi_controller.rb
class TranslateCnToViController < ApplicationController
  def index
    @src_nmt = read_src_file "/home/trinhphong/Desktop/nmt/run/input.cn"
    @tgt_nmt = read_tgt_file "/home/trinhphong/Desktop/nmt/run/output_infer_cn_vi"

    @src_smt = read_src_file "/home/trinhphong/moses/run/input.cn"
    @tgt_smt = read_tgt_file "/home/trinhphong/moses/run/output_infer_cn_vi"

    @expect_tgt  = read_src_file "/home/trinhphong/translate_system/expect/expect_cn_vi"

    @bleu_nmt = read_bleu_file "/home/trinhphong/translate_system/expect/bleu.nmt.cn_vi"
    @bleu_smt = read_bleu_file "/home/trinhphong/translate_system/expect/bleu.smt.cn_vi"
  end

  def translate
    translate_nmt
    translate_smt
    clear_bleu
    redirect_to cn_to_vi_path
  end

  def mark
    ef = File.open("/home/trinhphong/translate_system/expect/expect_cn_vi", "w+")
    ef.write params[:expect_tgt]
    ef.close

    `~/moses/mosesdecoder/scripts/generic/multi-bleu.perl -lc /home/trinhphong/translate_system/expect/expect_cn_vi < /home/trinhphong/Desktop/nmt/run/output_infer_cn_vi > /home/trinhphong/translate_system/expect/bleu.nmt.cn_vi`
    `~/moses/mosesdecoder/scripts/generic/multi-bleu.perl -lc /home/trinhphong/translate_system/expect/expect_cn_vi < /home/trinhphong/moses/run/output_infer_cn_vi > /home/trinhphong/translate_system/expect/bleu.smt.cn_vi`
    redirect_to cn_to_vi_path
  end

  def translate_nmt
    ef = File.open("/home/trinhphong/Desktop/nmt/run/input.cn", "w+")
    ef.write params[:src].chars.join(' ').strip
    ef.close

    system('cd /home/trinhphong/Desktop/nmt && python -m nmt.nmt --out_dir=/home/trinhphong/Desktop/nmt/tuning-output/output-cn-vi --inference_input_file=/home/trinhphong/Desktop/nmt/run/input.cn --inference_output_file=/home/trinhphong/Desktop/nmt/run/output_infer_cn_vi')
  end

  def translate_smt
    `echo #{params[:src].chars.join(' ').strip} > /home/trinhphong/moses/run/input.cn`
    `/home/trinhphong/moses/mosesdecoder/bin/moses -f /home/trinhphong/moses/working-cn-vi-no-token/filtered-test/moses.ini < /home/trinhphong/moses/run/input.cn > /home/trinhphong/moses/run/output_infer_cn_vi`
  end

  def clear
    clear_file
    redirect_to cn_to_vi_path
  end

  private

  def clear_file
    `echo '-' > /home/trinhphong/Desktop/nmt/run/input.cn`
    `echo '-' > /home/trinhphong/Desktop/nmt/run/output_infer_cn_vi`
    `echo '-' > /home/trinhphong/moses/run/input.cn`
    `echo '-' > /home/trinhphong/moses/run/output_infer_cn_vi`
    `echo '-' > /home/trinhphong/translate_system/expect/expect_cn_vi`
    clear_bleu
  end

  def clear_bleu
    `echo '-' > /home/trinhphong/translate_system/expect/bleu.nmt.cn_vi`
    `echo '-' > /home/trinhphong/translate_system/expect/bleu.smt.cn_vi`
  end
end

app/controllers/translate_controller.rb
class TranslateController < ApplicationController
  def index
    @src_nmt = read_src_file "/home/trinhphong/Desktop/nmt/run/input.en"
    @tgt_nmt = read_tgt_file "/home/trinhphong/Desktop/nmt/run/output_infer"

    @src_smt = read_src_file "/home/trinhphong/moses/run/input.en"
    @tgt_smt = read_tgt_file "/home/trinhphong/moses/run/output_infer"

    @expect_tgt  = read_src_file "/home/trinhphong/translate_system/expect/expect"

    @bleu_nmt = read_bleu_file "/home/trinhphong/translate_system/expect/bleu.nmt"
    @bleu_smt = read_bleu_file "/home/trinhphong/translate_system/expect/bleu.smt"
  end

  def translate
    translate_nmt
    translate_smt
    clear_bleu
    redirect_to root_path
  end

  def mark
    ef = File.open("/home/trinhphong/translate_system/expect/expect", "w+")
    ef.write params[:expect_tgt]
    ef.close

    `~/moses/mosesdecoder/scripts/generic/multi-bleu.perl -lc /home/trinhphong/translate_system/expect/expect < /home/trinhphong/Desktop/nmt/run/output_infer > /home/trinhphong/translate_system/expect/bleu.nmt`
    `~/moses/mosesdecoder/scripts/generic/multi-bleu.perl -lc /home/trinhphong/translate_system/expect/expect < /home/trinhphong/moses/run/output_infer > /home/trinhphong/translate_system/expect/bleu.smt`
    redirect_to root_path
  end

  def translate_nmt
    ef = File.open("/home/trinhphong/Desktop/nmt/run/input.en", "w+")
    ef.write params[:src].strip
    ef.close

    system('cd /home/trinhphong/Desktop/nmt && python -m nmt.nmt --out_dir=/home/trinhphong/Desktop/nmt/tuning-output/output-en-vi-full --inference_input_file=/home/trinhphong/Desktop/nmt/run/input.en --inference_output_file=/home/trinhphong/Desktop/nmt/run/output_infer')
  end

  def translate_smt
    `echo #{params[:src].strip} > /home/trinhphong/moses/run/input.en`
    `/home/trinhphong/moses/mosesdecoder/bin/moses -f /home/trinhphong/moses/working-full/fitered-test/moses.ini < /home/trinhphong/moses/run/input.en > /home/trinhphong/moses/run/output_infer`
  end

  def clear
    clear_file
    redirect_to root_path
  end

  private

  def clear_file
    `echo '-' > /home/trinhphong/Desktop/nmt/run/input.en`
    `echo '-' > /home/trinhphong/Desktop/nmt/run/output_infer`
    `echo '-' > /home/trinhphong/moses/run/input.en`
    `echo '-' > /home/trinhphong/moses/run/output_infer`
    `echo '-' > /home/trinhphong/translate_system/expect/expect`
    clear_bleu
  end

  def clear_bleu
    `echo '-' > /home/trinhphong/translate_system/expect/bleu.nmt`
    `echo '-' > /home/trinhphong/translate_system/expect/bleu.smt`
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translate_cn_to_vi_helper.rb
module TranslateCnToViHelper
end

app/helpers/translate_helper.rb
module TranslateHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TranslateSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/translate/index.html.erb
<div class="container main-container">
  <div class="row">
    <%= form_tag translating_path do %>
      <div class="col-md-5 src-field">
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">SRC</span>
          <%= text_area_tag :src, @src_nmt == '-' ? '' : @src_nmt, class: 'form-control my-text-field' %>
        </div>
      </div>
      <div class="col-md-1 button-action-group">
        <%= submit_tag 'Run', class: 'btn btn-primary form-control run-button' %>
    <% end %>
        <%= form_tag clearing_path do %>
          <%= submit_tag 'Clear', class: 'btn btn-danger form-control'  %>
        <% end %>
      </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">NMT</span>
            <%= text_area_tag :tgt_nmt, @tgt_nmt == '-' ? '' : @tgt_nmt, class: 'form-control my-text-field', readonly: true %>
            <span class="input-group-addon" id="basic-addon2"><%= @bleu_nmt %></span>
          </div>
        </div>
      </div>
      <%= form_tag marking_path do %>
        <div class="row">
          <div class="col-md-12">
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon3">EXP</span>
              <%= text_area_tag :expect_tgt, @expect_tgt == '-' ? '' : @expect_tgt, class: 'form-control my-text-field' %>
              <span class="input-group-btn">
                <%= submit_tag 'Mark', class: 'btn btn-success mark-button'  %>
              </span>
            </div>
          </div>
          <div class="col-md-2">
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon4">SMT</span>
            <%= text_area_tag :tgt_smt, @tgt_smt == '-' ? '' : @tgt_smt, class: 'form-control my-text-field', readonly: true %>
            <span class="input-group-addon" id="basic-addon5"><%= @bleu_smt %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/translate_cn_to_vi/index.html.erb
<div class="container main-container">
  <div class="row">
    <%= form_tag translating_cn_vi_path do %>
      <div class="col-md-5 src-field">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= link_to 'Chinese-Vietnamese', '#', class: 'btn btn-default form-control', readonly: true %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= link_to 'English-Vietnamese', root_path, class: 'btn btn-default form-control' %>
            </div>
          </div>
        </div>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">SRC</span>
          <%= text_area_tag :src, @src_nmt == '-' ? '' : @src_nmt, class: 'form-control my-text-field' %>
        </div>
      </div>
      <div class="col-md-1 button-action-group">
        <%= submit_tag 'Run', class: 'btn btn-primary form-control run-button' %>
    <% end %>
        <%= form_tag clearing_cn_vi_path do %>
          <%= submit_tag 'Clear', class: 'btn btn-danger form-control'  %>
        <% end %>
      </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">NMT</span>
            <%= text_area_tag :tgt_nmt, @tgt_nmt == '-' ? '' : @tgt_nmt, class: 'form-control my-text-field', readonly: true %>
            <span class="input-group-addon" id="basic-addon2"><%= @bleu_nmt %></span>
          </div>
        </div>
      </div>
      <%= form_tag marking_cn_vi_path do %>
        <div class="row">
          <div class="col-md-12">
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon3">EXP</span>
              <%= text_area_tag :expect_tgt, @expect_tgt == '-' ? '' : @expect_tgt, class: 'form-control my-text-field' %>
              <span class="input-group-btn">
                <%= submit_tag 'Mark', class: 'btn btn-success mark-button'  %>
              </span>
            </div>
          </div>
          <div class="col-md-2">
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon4">SMT</span>
            <%= text_area_tag :tgt_smt, @tgt_smt == '-' ? '' : @tgt_smt, class: 'form-control my-text-field', readonly: true %>
            <span class="input-group-addon" id="basic-addon5"><%= @bleu_smt %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>